[functions.telegram-bot]
verify_jwt = false

[functions.yasno-api]
verify_jwt = false

[functions.notification-checker]
verify_jwt = false

[functions.schedule-change-checker]
verify_jwt = false

[functions.user-prefs]
verify_jwt = false
